### ISSUE TITLE
hplot error

### ISSUE THREAD

**Issue by tlp30** [BenGutierrez/meica-figure#2]
I get the following error running Meica_Report, which seems to relate to hplot being deprecated.  How do I get around this? 

PlotScript error:
Traceback (most recent call last):
  File "/home/tanya/anaconda3/envs/Py2.7/lib/python2.7/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "Report_Figures/bokeh_plot.py", line 20, in <module>
    from bokeh.plotting      import figure, gridplot, output_file, show, hplot, ### vplot
ImportError: cannot import name hplot

Makefile:53: recipe for target 'html' failed
make: *** [html] Error 2

**Comment by BenGutierrez** [comment]
Hi tlp30,

Unfortunately I have not update the code for this program as you have noticed in some time.  It has been several years since I have looked at the program and honestly don't have easy access to a data set to even run it on any more.  However I think that there are 2 ways this can be solved.  
1) You can comment out lines 217-218 of Meica_report.py and lines 35-39 of rst_files.py.  This "should" prevent this error from occurring by not using the bokeh module.  This will unfortunately remove the graph it was calling creating and calling.  I think this will work, but again, I do not have a way to test it.
2)  You can update bokeh_plot.py with the new format that Bokeh uses. This may take some time as Bokeh has changed pretty extensively since I used it, but it looks like it was simplified in many ways.

I am sorry I cannot be more helpful.  Please let me know how this goes.
Ben
